name: 03 - Workflow Runners
on: workflow_dispatch
jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running on Ubuntu runner"
                echo ${{runner.name}} ${{runner.os}} ${{runner.arch}}
    windows-echo:
        runs-on: windows-latest
        steps:
            - name: Show OS
              shell: bash
              run: |
                echo "This job is running on Windows runner"
                echo ${{runner.name}} ${{runner.os}} ${{runner.arch}}
    mac-echo:
        runs-on: macos-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running on MacOS runner"
                echo ${{runner.name}} ${{runner.os}} ${{runner.arch}}